import {
  LayoutDashboard, Home, Settings, User, LogOut, LogIn,
  Star, Heart, Bookmark,
  Folder, File, Image, Video, Music,
  Code, Terminal, Database, Server, Cloud,
  Globe, Link, ExternalLink,
  ShoppingCart, CreditCard,
  Calendar, Clock,
  Search, Menu, X, ChevronDown, ChevronRight,
  Plus, Minus, Edit, Trash,
  Smartphone, Laptop, Tablet,
  Zap, Activity,
  Shield, Lock,
  Mail, MessageSquare,
  Twitter, Facebook, Instagram, Github,
  Sun, Moon,
  Map, MapPin,
  Camera,
  Book, GraduationCap,
  Briefcase,
  Wrench,
  Cpu, HardDrive,
  Wifi, Bluetooth,
  Battery,
  AlertCircle, AlertTriangle, CheckCircle, Info,
  HelpCircle,
  Hash, List, MoreHorizontal, MoreVertical,
  Share, Download, Upload,
  Eye, EyeOff,
  Bell,
  Play, Pause,
  Volume2, VolumeX,
  Mic, MicOff,
  Monitor,
  Printer,
  Save,
  Trash2,
  Archive,
  Inbox,
  Send,
  Paperclip,
  Smile,
  ThumbsUp, ThumbsDown,
  Gift,
  Award,
  Flag,
  Target,
  Compass,
  Anchor,
  CloudRain, CloudSnow, CloudLightning,
  Umbrella,
  Coffee,
  Utensils,
  Beer,
  ShoppingBag,
  Truck,
  Package,
  DollarSign,
  PieChart, BarChart, LineChart,
  Users,
  Building,
  Key,
  Unlock,
  ShieldCheck, ShieldAlert,
  FileText, FilePlus, FileMinus,
  FolderPlus, FolderMinus,
  Film,
  Headphones,
  Speaker,
  Radio,
  Tv,
  Cast,
  Airplay,
  Chrome,
  Command,
  Disc,
  Layers,
  Box,
  Component,
  Figma,
  Framer,
  Hexagon,
  Layout,
  LayoutGrid,
  LayoutList,
  Maximize, Minimize,
  MousePointer,
  Move,
  PenTool,
  Scissors,
  Type,
  Underline,
  Bold, Italic,
  AlignLeft, AlignCenter, AlignRight, AlignJustify,
  ListOrdered,
  Check,
  CheckSquare,
  Square,
  Circle,
  Triangle,
  XCircle, XSquare,
  PlusCircle, PlusSquare,
  MinusCircle, MinusSquare,
  ArrowRight, ArrowLeft, ArrowUp, ArrowDown,
  ChevronUp, ChevronLeft,
  ChevronsLeft, ChevronsRight, ChevronsUp, ChevronsDown,
  RefreshCw, RefreshCcw,
  RotateCw, RotateCcw,
  Repeat,
  Shuffle,
  Power,
  ZoomIn, ZoomOut,
  Filter,
  SortAsc, SortDesc,
  Watch,
  Timer,
  Hourglass,
  Wind,
  Droplets,
  Thermometer,
  Frown,
  Meh,
  UserPlus, UserMinus, UserCheck, UserX,
  Medal,
  Trophy,
  Tag,
  MessageCircle,
  Phone,
  PhoneCall, PhoneIncoming, PhoneOutgoing, PhoneMissed, PhoneOff,
  Volume1,
  GripVertical
} from 'lucide-react';

// Manually map icons to avoid bundling all of lucide-react
export const IconsMap: Record<string, React.ElementType> = {
  LayoutDashboard, Home, Settings, User, LogOut, LogIn,
  Star, Heart, Bookmark,
  Folder, File, Image, Video, Music,
  Code, Terminal, Database, Server, Cloud,
  Globe, Link, ExternalLink,
  ShoppingCart, CreditCard,
  Calendar, Clock,
  Search, Menu, X, ChevronDown, ChevronRight,
  Plus, Minus, Edit, Trash,
  Smartphone, Laptop, Tablet,
  Zap, Activity,
  Shield, Lock,
  Mail, MessageSquare,
  Twitter, Facebook, Instagram, Github,
  Sun, Moon,
  Map, MapPin,
  Camera,
  Book, GraduationCap,
  Briefcase,
  Wrench,
  Cpu, HardDrive,
  Wifi, Bluetooth,
  Battery,
  AlertCircle, AlertTriangle, CheckCircle, Info,
  HelpCircle,
  Hash, List, MoreHorizontal, MoreVertical,
  Share, Download, Upload,
  Eye, EyeOff,
  Bell,
  Play, Pause,
  Volume2, VolumeX,
  Mic, MicOff,
  Monitor,
  Printer,
  Save,
  Trash2,
  Archive,
  Inbox,
  Send,
  Paperclip,
  Smile,
  ThumbsUp, ThumbsDown,
  Gift,
  Award,
  Flag,
  Target,
  Compass,
  Anchor,
  CloudRain, CloudSnow, CloudLightning,
  Umbrella,
  Coffee,
  Utensils,
  Beer,
  ShoppingBag,
  Truck,
  Package,
  DollarSign,
  PieChart, BarChart, LineChart,
  Users,
  Building,
  Key,
  Unlock,
  ShieldCheck, ShieldAlert,
  FileText, FilePlus, FileMinus,
  FolderPlus, FolderMinus,
  Film,
  Headphones,
  Speaker,
  Radio,
  Tv,
  Cast,
  Airplay,
  Chrome,
  Command,
  Disc,
  Layers,
  Box,
  Component,
  Figma,
  Framer,
  Hexagon,
  Layout,
  LayoutGrid,
  LayoutList,
  Maximize, Minimize,
  MousePointer,
  Move,
  PenTool,
  Scissors,
  Type,
  Underline,
  Bold, Italic,
  AlignLeft, AlignCenter, AlignRight, AlignJustify,
  ListOrdered,
  Check,
  CheckSquare,
  Square,
  Circle,
  Triangle,
  XCircle, XSquare,
  PlusCircle, PlusSquare,
  MinusCircle, MinusSquare,
  ArrowRight, ArrowLeft, ArrowUp, ArrowDown,
  ChevronUp, ChevronLeft,
  ChevronsLeft, ChevronsRight, ChevronsUp, ChevronsDown,
  RefreshCw, RefreshCcw,
  RotateCw, RotateCcw,
  Repeat,
  Shuffle,
  Power,
  ZoomIn, ZoomOut,
  Filter,
  SortAsc, SortDesc,
  Watch,
  Timer,
  Hourglass,
  Wind,
  Droplets,
  Thermometer,
  Frown,
  Meh,
  UserPlus, UserMinus, UserCheck, UserX,
  Medal,
  Trophy,
  Tag,
  MessageCircle,
  Phone,
  PhoneCall, PhoneIncoming, PhoneOutgoing, PhoneMissed, PhoneOff,
  Volume1,
  GripVertical
};

export const IconRenderer = ({ iconName, className }: { iconName: string | null; className?: string }) => {
  if (!iconName) return null;
  const IconComponent = IconsMap[iconName];
  if (!IconComponent) return null;
  return <IconComponent className={className} />;
};
