import {
  LayoutDashboard, Home, Settings, User, LogOut, LogIn,
  Star, Heart, Bookmark,
  Folder, File, Image, Video, Music,
  Code, Terminal, Database, Server, Cloud,
  Globe, Link, ExternalLink,
  ShoppingCart, CreditCard,
  Calendar, Clock,
  Search, Menu, X, ChevronDown, ChevronRight,
  Plus, Minus, Edit, Trash,
  Smartphone, Laptop, Tablet,
  Zap, Activity,
  Shield, Lock,
  Mail, MessageSquare,
  Twitter, Facebook, Instagram, Github,
  Sun, Moon,
  Map, MapPin,
  Camera,
  Book, GraduationCap,
  Briefcase,
  Wrench,
  Cpu, HardDrive,
  Wifi, Bluetooth,
  Battery,
  AlertCircle, AlertTriangle, CheckCircle, Info,
  HelpCircle,
  Hash, List, MoreHorizontal, MoreVertical,
  Share, Download, Upload,
  Eye, EyeOff,
  Bell,
  Play, Pause,
  Volume2, VolumeX,
  Mic, MicOff,
  Monitor,
  Printer,
  Save,
  Archive,
  Inbox,
  Send,
  Paperclip,
  Smile,
  ThumbsUp,
  Gift,
  Award,
  Flag,
  Target,
  Compass,
  Anchor,
  Coffee,
  ShoppingBag,
  Truck,
  Package,
  DollarSign,
  PieChart, BarChart, LineChart,
  Users,
  Building,
  Key,
  FileText,
  Film,
  Headphones,
  Speaker,
  Tv,
  Chrome,
  Command,
  Layers,
  Box,
  Component,
  Layout,
  Maximize, Minimize,
  MousePointer,
  Move,
  PenTool,
  Type,
  Check,
  ArrowRight, ArrowLeft, ArrowUp, ArrowDown,
  ChevronUp, ChevronLeft,
  RefreshCw,
  Power,
  Filter,
  Tag,
  MessageCircle,
  Phone,
  GripVertical,
  FolderTree,
  CloudCog,
  Loader2,
  Import,
  FileJson,
  FileCode,
  ShieldCheck
} from 'lucide-react';

export const IconsMap: Record<string, React.ElementType> = {
  LayoutDashboard, Home, Settings, User, LogOut, LogIn,
  Star, Heart, Bookmark,
  Folder, File, Image, Video, Music,
  Code, Terminal, Database, Server, Cloud,
  Globe, Link, ExternalLink,
  ShoppingCart, CreditCard,
  Calendar, Clock,
  Search, Menu, X, ChevronDown, ChevronRight,
  Plus, Minus, Edit, Trash,
  Smartphone, Laptop, Tablet,
  Zap, Activity,
  Shield, Lock,
  Mail, MessageSquare,
  Twitter, Facebook, Instagram, Github,
  Sun, Moon,
  Map, MapPin,
  Camera,
  Book, GraduationCap,
  Briefcase,
  Wrench,
  Cpu, HardDrive,
  Wifi, Bluetooth,
  Battery,
  AlertCircle, AlertTriangle, CheckCircle, Info,
  HelpCircle,
  Hash, List, MoreHorizontal, MoreVertical,
  Share, Download, Upload,
  Eye, EyeOff,
  Bell,
  Play, Pause,
  Volume2, VolumeX,
  Mic, MicOff,
  Monitor,
  Printer,
  Save,
  Archive,
  Inbox,
  Send,
  Paperclip,
  Smile,
  ThumbsUp,
  Gift,
  Award,
  Flag,
  Target,
  Compass,
  Anchor,
  Coffee,
  ShoppingBag,
  Truck,
  Package,
  DollarSign,
  PieChart, BarChart, LineChart,
  Users,
  Building,
  Key,
  FileText,
  Film,
  Headphones,
  Speaker,
  Tv,
  Chrome,
  Command,
  Layers,
  Box,
  Component,
  Layout,
  Maximize, Minimize,
  MousePointer,
  Move,
  PenTool,
  Type,
  Check,
  ArrowRight, ArrowLeft, ArrowUp, ArrowDown,
  ChevronUp, ChevronLeft,
  RefreshCw,
  Power,
  Filter,
  Tag,
  MessageCircle,
  Phone,
  GripVertical,
  FolderTree,
  CloudCog,
  Loader2,
  Import,
  FileJson,
  FileCode,
  ShieldCheck
};

export const IconRenderer = ({ iconName, className }: { iconName: string | null; className?: string }) => {
  if (!iconName) return null;
  const IconComponent = IconsMap[iconName];
  if (!IconComponent) return null;
  return <IconComponent className={className} />;
};
